config/routes.rb
Rails.application.routes.draw do
  resources :smos
  resources :games
  resources :videos

  resources :articles

  resources :news

  resources :lobbies

  get 'profile/myprofile'

  get 'profile/profile'

  get 'profile/new'

  get 'profile/create'

  get 'auth/index'

  get 'translations' => 'translations#index'

  get 'faq' => 'faq#index'

  resources :sandboxes
  root 'main#index'
  get 'competitions' => 'competitions#index'

  get 'top' => 'top#index'
  post 'auth/steam/callback' => 'auth#auth_callback'
  get 'logout' => 'auth#logout'

  root to: 'main#index', as: 'main'
  get 'myprofile' => 'profile#myprofile'
  get 'profile' => 'profile#profile'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/lobby.rb
class Lobby < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/sandbox.rb
class Sandbox < ActiveRecord::Base
end

app/models/smo.rb
class Smo < ActiveRecord::Base
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/sandboxes_controller.rb
class SandboxesController < ApplicationController
  before_action :set_sandbox, only: [:show, :edit, :update, :destroy]

  # GET /sandboxes
  # GET /sandboxes.json
  def index
    @sandboxes = Sandbox.all
  end

  # GET /sandboxes/1
  # GET /sandboxes/1.json
  def show
  end

  # GET /sandboxes/new
  def new
    @sandbox = Sandbox.new
  end

  # GET /sandboxes/1/edit
  def edit
  end

  # POST /sandboxes
  # POST /sandboxes.json
  def create
    @sandbox = Sandbox.new(sandbox_params)

    respond_to do |format|
      if @sandbox.save
        format.html { redirect_to @sandbox, notice: 'Sandbox was successfully created.' }
        format.json { render :show, status: :created, location: @sandbox }
      else
        format.html { render :new }
        format.json { render json: @sandbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sandboxes/1
  # PATCH/PUT /sandboxes/1.json
  def update
    respond_to do |format|
      if @sandbox.update(sandbox_params)
        format.html { redirect_to @sandbox, notice: 'Sandbox was successfully updated.' }
        format.json { render :show, status: :ok, location: @sandbox }
      else
        format.html { render :edit }
        format.json { render json: @sandbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sandboxes/1
  # DELETE /sandboxes/1.json
  def destroy
    @sandbox.destroy
    respond_to do |format|
      format.html { redirect_to sandboxes_url, notice: 'Sandbox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sandbox
      @sandbox = Sandbox.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sandbox_params
      params[:sandbox]
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
    def top_callback
    auth = request.env['omniauth.auth']
    session[:user] = { :nickname => auth.info['nickname'],
                       :image => auth.info['image'],
                       :uid => auth.uid }
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/lobbies_helper.rb
module LobbiesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sandboxes_helper.rb
module SandboxesHelper
end

app/helpers/smos_helper.rb
module SmosHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/sandboxes/_form.html.haml
= form_for @sandbox do |f|
  - if @sandbox.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sandbox.errors.count, "error")} prohibited this sandbox from being saved:"
      %ul
        - @sandbox.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/sandboxes/edit.html.haml
%h1 Editing sandbox

= render 'form'

= link_to 'Show', @sandbox
\|
= link_to 'Back', sandboxes_path

app/views/sandboxes/index.html.haml
%h1 Listing sandboxes

%table
  %thead
    %tr
      %th
      %th
      %th
      
  %tbody
    - @sandboxes.each do |sandbox|
      %tr
        %td= link_to 'Show', sandbox
        %td= link_to 'Edit', edit_sandbox_path(sandbox)
        %td= link_to 'Destroy', sandbox, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sandbox', new_sandbox_path

app/views/sandboxes/new.html.haml
%h1 New sandbox

= render 'form'

= link_to 'Back', sandboxes_path

app/views/sandboxes/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_sandbox_path(@sandbox)
\|
= link_to 'Back', sandboxes_path